### ISSUE TITLE
LEARNING Branch-merging

### ISSUE THREAD

**Issue by bobang1992** [AthirK/Quiz-app-with-agila-methods#14]
We studied how to merge in GIT Hub to teach our team how to utilize merging themselves in the future in this project

Create issue -> create branch within issue -> solve issue -> create pull request -> code review -> merge

**Comment by Zeldoz** [comment]
har sett

**Comment by swestlund** [comment]
We studied the masters and found enlightenment. We now have all the info. 

Create issue -> create branch within issue -> solve issue -> create pull request -> code review -> merge
