### ISSUE TITLE
Menu User-Story game-menu Implementation

### ISSUE THREAD

**Issue by Zeldoz** [AthirK/Quiz-app-with-agila-methods#38]
## Description

As a user I want to be able to see another menu after the "username login menu" that gives me the options to for ex help, shop, categories to start quiz etc.

## Acceptance criteria

- [ ] The game menu should come up after you input a username,
- [ ] The game menu should give you options to choose from either by putting in the command or by selecting a number assigned to options from the menu list.

## Technical notes

- implement a game menu class
- run different commands depending on menu choices

## Definition of Done

- [x] Koden är skriven och testad
- [x] Dokumentation är uppdaterad
- [x] Pull request är skapad
- [ ] Code review är genomförd
- [ ] Alla tester går igenom

**Comment by AthirK** [comment]
![Image](https://github.com/user-attachments/assets/a59ebbbe-d618-4a4a-b853-71cf653ee40c)
